### ISSUE TITLE
Thanks for your great work

### ISSUE THREAD

**Issue by tan-it** [ysgclight/Carla_iLQR_MPC#3]
Your ilqr_jax_MPC code is not running I tried some modifications in code but still it is not working in Jax 0.2.9

**Comment by YukunXia** [comment]
Sorry for the inconvenience. I haven't closely looked into this project for a while.

As a temporary solution, would you mind downgrading your jax to version 0.1.68 to see if you could run ilqr_jax_MPC? The code was very likely to be tested on that jax version.

**Comment by tan-it** [comment]
> Sorry for the inconvenience. I haven't closely looked into this project for a while.
> 
> As a temporary solution, would you mind downgrading your jax to version 0.1.68 to see if you could run ilqr_jax_MPC? The code was very likely to be tested on that jax version.

I downgraded my Jax already but another error coming from jaxlib . actually I am windows user so no jaxlib version support for Jax 0.1.68 .I am trying to make another code which will run on Jax 0.2.9 . If I get success then definitely I will post here .Thank you for your reply

**Comment by YukunXia** [comment]
Yeah, I ran my code on Ubuntu, so that could be another difference. Feel free to send a pull request if you achieve similar results on Jax 0.2.9.
